return {
	Black = {
		"____? Theres an App for that",
		"What's that smell?",
		"AHHH! I want _____!",
		"Why cant I sleep at Night?",
		"What's that Smell?",
		"I have 99 Problems but _____ ain't One",
		"Whats the new Happy Meal Toy from McDonalds?",
		"Instead of coal, Santa now gives the bad children _____.",
		"I have ____, and you can't have it",
		"I have ____, and you can't touch it",
		"____? High five bro!",
		"Next from JK Rowling: Harry Potter and ____",
		"____? DECLARE WAR",
		"What are my parents hiding from me?",
		"What did I bring back from Holiday?",
		"____! It's a trap!",
		"What's my secret power?",
		"The class field trip was completely ruined by ____.",
		"What gets better with age?",
		"____: kid tested and mother approved!",
		"What is simply the Cutest?",
		"Studies show that lab rats navigate mazes 50% faster after being exposed to ____",
		"Why do I hurt all over?",
		"When I am a billionaire, I shall create a 50 foot tall statue of ____.",
		"What never fails to liven up the party?",
		"What's the new diet?",
		"____ Smells GREAT in the Morning!",
		"____? Thats so last month!",
		"No sense in crying over ____",
		"The Power of Love is useless against ____",
		"Had a bad day because I saw ____",
		"Nothing feels better seeing ____ get blown up.",
		"Ask your Doctor if ____ is really good for you",
		"Disney Presents: ____ on Ice!",
		"I was into ____ before it became hip",
		"In recent news, Apple just released ____",
		"____ is simply the worst.",
		"Im sick, and the only cure is ____",
		"Girl Scouts even have a badge for ____",
		"____ is good for any Friendship!",
		"____: Friendship tested and approved!",
		"DC Presents: Batman and his sidekick, ____",
		"Marvel presents their new superhero, ____-man!",
		"What do I like with my toast in the morning?",
		"What will be on my tombstone when I die?",
		"How did he die?",
		"I've seen to much of ____ for a lifetime.",
		"What is man's worst fear?",
		"Next on Reddit, /r/____",
		"We went hiking, and ran into ____",
		"Rob Schneider is a ____! Coming Soon!",
		"____, Fun for the whole family!",
		"My secret ingredent for Mac & Cheese is ____",
		"What ended my last relationship?",
		"I learned about ____ the hard way.",
		"My precious ____",
		"Brace yourselves, ____ is coming!",
		"TAARS, please activate ____",
		"Help! I lost my ____",
		"I find your lack of ____ oddly disturbing",
		"I know you are, but what am I?",
		"____ is against the law?",
		"____, Awesome in theory! Kind of mess in practice.",
		"Dear Mom,\nCamp is fun! The other day, a campter taught me about ____!",
		"What's my secret power?"
	},
	DoubleBlack = {
		"The Academy Award for _____ goes to _____!",
		"For my next trick I will pull _____ out of _____!",
		"_____ is a slipery slope that leads to _____",
		"In a world doomed by _____, our only hope is _____.",
		"Step 1: Try _____\nStep 2: Use _____\nStep 3: Profit.",
		"I never truely understood _____ until I encountered _____",
		"When I Hallucinate, _____ turns into _____",
		"I used _____ to clean up _____",
		"Adding _____ to _____ makes them taste tens times better",
		"_____ A Day Keeps _____ Away",
		"_____ Works Great with _____",
		"_____ goes TERRIBLY with _____",
		"This years top-selling album of '_____' goes to _____",
		"If you cant handle _____, you should stay away from _____!",
		"_____ + _____ = Overkill",
		"Careful, _____ leads to _____",
		"Having problems with _____? Try _____!"
	},
	White = {
		"A Disappointing Party",
		"Puppies",
		"Dying",
		"Being on Fire",
		"A Lifetime of Sadness",
		"Crippling Debt",
		"Republicans",
		"The Big Bang",
		"Men",
		"Making a Pouty Face",
		"Pandas",
		"A Drive by Shooting",
		"Ronald Reagan",
		"Morgan Freeman",
		"Tom Cruise",
		"Obesity",
		"Repression",
		"Attitude",
		"Party Failures",
		"The American Dream",
		"The Folly of Man",
		"Goats Eating Cans",
		"Doing the Right Thing",
		"The Muddy Hand",
		"Chucky Cheese",
		"A Powerful Behind",
		"Saxophone Solos",
		"Cuddling",
		"Dwayne \"The Rock\" Johnson",
		"Geese.",
		"Minecraft",
		"Losing your Pants at Walmart",
		"The Big Bad Wolf",
		"My Ebola Problem",
		"Going to Ikea",
		"A Giant Half-Eaten Cookie",
		"Poor People",
		"Rich People",
		"Pillow Fights",
		"Purple Kool-Aid",
		"Nicolas Cage",
		"Wizards",
		"Not Caring about the Third World",
		"Michelle Obama's Arms",
		"A Good Sniff",
		"Stephen Hawking Singing",
		"Oprah Crying while eating a Hot Pocket",
		"A VERY Angry Black Woman",
		"Pompeii",
		"The Biggest Loser",
		"Autistic Kids",
		"Tape that Sticks to your Fingers",
		"A Man-Sized Hamster Wheel",
		"Giving into the Dark Side for a Cookie",
		"Your Face",
		"Black Holes",
		"John Shedletsky's Laugh",
		"Harry Potters Wizarding Robes",
		"Editing Wikipedia to win an Argument",
		"Feminists with a Beard",
		"Gingers",
		"Hello Kitty in Tears",
		"Using a Public Restroom for longer than 15 Minutes",
		"My Mothers Sheep Issue",
		"A Brony Convention",
		"The Civil War",
		"Liam Neeson Punching Wolves",
		"Ghosts that aren't really Ghosts",
		"A Crabby Patty",
		"Jell-O Puddin' Pops",
		"The Problem known as Mudbloods.",
		"Elephants touching their toes",
		"Being unable to Breathe",
		"Active Listening",
		"Taylor Swift",
		"A Peter Piper Ball Pit",
		"Beyonce",
		"A Hardcore Brony",
		"Women getting hit with Shovels",
		"Girls on Fire",
		"A Church Choir singing 'Let It Go'",
		"Professor Snape",
		"Basic Bros",
		"LEEEEROY JENKINS!",
		"Dumbledore",
		"The Zombie Apocalypse",
		"Me",
		"You",
		"Cripple Fight",
		"Hackers",
		"Bad Facebook Pictures",
		"Too many Tweets",
		"Peanut Butter & Jelly",
		"The Google Empire",
		"The inability to form meaningful relationships",
		"A pizza guy who screwed up",
		"Africa",
		"Hipsters",
		"Poor life choices",
		"The Internet",
		"A Low Standard of Living",
		"A Disappointing Salad",
		"Jeff Goldblum",
		"Life in General",
		"Past Failures",
		"The Future",
		"Land Mines",
		"Free ice cream, yo.",
		"Getting really worried about global warming",
		"Wearing an octopus for a hat",
		"Bullets",
		"Wearing glasses and sounding smart",
		"An ugly face.",
		"Mad hacky-sack skills",
		"The Sun engulfing the Earth",
		"Existing.",
		"Robots who just want to Party",
		"Words, words, words",
		"Important news about Taylor Swift",
		"Exploding pidgeons",
		"Friendly fire",
		"A ton of candy",
		"Funky freash rhymes",
		"Fire ants",
		"Superman",
		"Nunchuck moves",
		"Chuck Norris",
		"Fun and interesting facts about rocks",
		"A one-way ticket to India",
		"A cloud of ash that darkens the earth for a century",
		"Being rich",
		"Five-Dollar Footlongs from Subway",
		"Catapults",
		"Making a friend",
		"The Purge",
		"Advice from an old man",
		"Socks. Lots of socks.",
		"The mind of a child",
		"The Economy",
		"A self-microwaving burrito",
		"Having a degree in a field no one has ever heard about",
		"The Medieval times",
		"Science",
		"Being fabulous",
		"The hiccups",
		"Grandma",
		"Grandpa",
		"Your father",
		"Your mother",
		"Darth Vader",
		"Yoda",
		"Kanye West",
		"Pewdiepie",
		"Too much cheese",
		"Generally having no idea whats going on",
		"Drinking a Capri Sun"
	}
}
